# Generated by Django 4.0.4 on 2022-07-11 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Following',
        ),
    ]
