# Generated by Django 4.0.4 on 2022-07-09 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Following',
        ),
    ]
