# Generated by Django 4.0.4 on 2022-07-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_excelfileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelFileUpload',
        ),
    ]
